/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microchip_mcp2221_HidFeatures */

#ifndef _Included_com_microchip_mcp2221_HidFeatures
#define _Included_com_microchip_mcp2221_HidFeatures
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_LoadDll
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1LoadDll
  (JNIEnv *, jobject);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetLibraryVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetLibraryVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetConnectedDevices
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetConnectedDevices
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_OpenByIndex
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1OpenByIndex
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_OpenBySN
 * Signature: (IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1OpenBySN
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_Close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1Close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_CloseAll
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1CloseAll
  (JNIEnv *, jobject);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_Reset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1Reset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetSpeed
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetSpeed
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetAdvancedCommParams
 * Signature: (JSS)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetAdvancedCommParams
  (JNIEnv *, jobject, jlong, jshort, jshort);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_I2cCancelCurrentTransfer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1I2cCancelCurrentTransfer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_I2cRead
 * Signature: (JIBZ[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1I2cRead
  (JNIEnv *, jobject, jlong, jint, jbyte, jboolean, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_I2cWrite
 * Signature: (JIBZ[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1I2cWrite
  (JNIEnv *, jobject, jlong, jint, jbyte, jboolean, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SmbusWriteByte
 * Signature: (JBZZBB)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SmbusWriteByte
  (JNIEnv *, jobject, jlong, jbyte, jboolean, jboolean, jbyte, jbyte);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SmbusReadByte
 * Signature: (JBZZB[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SmbusReadByte
  (JNIEnv *, jobject, jlong, jbyte, jboolean, jboolean, jbyte, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SmbusWriteWord
 * Signature: (JBZZB[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SmbusWriteWord
  (JNIEnv *, jobject, jlong, jbyte, jboolean, jboolean, jbyte, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SmbusReadWord
 * Signature: (JBZZB[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SmbusReadWord
  (JNIEnv *, jobject, jlong, jbyte, jboolean, jboolean, jbyte, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SmbusBlockWrite
 * Signature: (JBZZBS[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SmbusBlockWrite
  (JNIEnv *, jobject, jlong, jbyte, jboolean, jboolean, jbyte, jshort, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SmbusBlockRead
 * Signature: (JBZZBS[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SmbusBlockRead
  (JNIEnv *, jobject, jlong, jbyte, jboolean, jboolean, jbyte, jshort, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetManufacturerDescriptor
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetManufacturerDescriptor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetManufacturerDescriptor
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetManufacturerDescriptor
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetProductDescriptor
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetProductDescriptor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetProductDescriptor
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetProductDescriptor
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetSerialNumberDescriptor
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetSerialNumberDescriptor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetSerialNumberDescriptor
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetSerialNumberDescriptor
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetFactorySerialNumber
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetFactorySerialNumber
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetVidPid
 * Signature: (J[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetVidPid
  (JNIEnv *, jobject, jlong, jintArray, jintArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetVidPid
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetVidPid
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetInitialPinValues
 * Signature: (J[B[B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetInitialPinValues
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetInitialPinValues
 * Signature: (JBBBBB)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetInitialPinValues
  (JNIEnv *, jobject, jlong, jbyte, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetUsbPowerAttributes
 * Signature: (J[S[I)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetUsbPowerAttributes
  (JNIEnv *, jobject, jlong, jshortArray, jintArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetUsbPowerAttributes
 * Signature: (JSI)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetUsbPowerAttributes
  (JNIEnv *, jobject, jlong, jshort, jint);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetSerialNumberEnumerationEnable
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetSerialNumberEnumerationEnable
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetSerialNumberEnumerationEnable
 * Signature: (JB)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetSerialNumberEnumerationEnable
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetSecuritySetting
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetSecuritySetting
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetSecuritySetting
 * Signature: (JBLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetSecuritySetting
  (JNIEnv *, jobject, jlong, jbyte, jstring, jstring);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetPermanentLock
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetPermanentLock
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SendPassword
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SendPassword
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetInterruptEdgeSetting
 * Signature: (JB[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetInterruptEdgeSetting
  (JNIEnv *, jobject, jlong, jbyte, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetInterruptEdgeSetting
 * Signature: (JBB)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetInterruptEdgeSetting
  (JNIEnv *, jobject, jlong, jbyte, jbyte);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_ClearInterruptPinFlag
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1ClearInterruptPinFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetInterruptPinFlag
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetInterruptPinFlag
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetHardwareRevision
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetHardwareRevision
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetFirmwareRevision
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetFirmwareRevision
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetClockSettings
 * Signature: (JB[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetClockSettings
  (JNIEnv *, jobject, jlong, jbyte, jbyteArray, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetClockSettings
 * Signature: (JBBB)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetClockSettings
  (JNIEnv *, jobject, jlong, jbyte, jbyte, jbyte);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetGpioSettings
 * Signature: (JB[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetGpioSettings
  (JNIEnv *, jobject, jlong, jbyte, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetGpioSettings
 * Signature: (JB[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetGpioSettings
  (JNIEnv *, jobject, jlong, jbyte, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetGpioValues
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetGpioValues
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetGpioValues
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetGpioValues
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetGpioDirection
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetGpioDirection
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetGpioDirection
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetGpioDirection
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetDacVref
 * Signature: (JB[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetDacVref
  (JNIEnv *, jobject, jlong, jbyte, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetDacVref
 * Signature: (JBB)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetDacVref
  (JNIEnv *, jobject, jlong, jbyte, jbyte);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetDacValue
 * Signature: (JB[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetDacValue
  (JNIEnv *, jobject, jlong, jbyte, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetDacValue
 * Signature: (JBB)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetDacValue
  (JNIEnv *, jobject, jlong, jbyte, jbyte);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetAdcVref
 * Signature: (JB[B)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetAdcVref
  (JNIEnv *, jobject, jlong, jbyte, jbyteArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_SetAdcVref
 * Signature: (JBB)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1SetAdcVref
  (JNIEnv *, jobject, jlong, jbyte, jbyte);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetAdcData
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetAdcData
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     com_microchip_mcp2221_HidFeatures
 * Method:    Mcp2221_GetLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_microchip_mcp2221_HidFeatures_Mcp2221_1GetLastError
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
